### ISSUE TITLE
[request] change quasar variables for theming

### ISSUE THREAD

**Issue by nigeltiany** [quasarframework/quasar-template-meteor#2] opened 2017-04-26 12:12 UTC
I have added a stylus meteor package (this one [by mquandalle](https://atmospherejs.com/mquandalle/stylus)), and on AppLayout.vue tested it out and it works
```styl 
<style lang="stylus">
   // @import '../quasar/quasar.variables.styl'
    .layout-content
        margin-top: -50px
</style> 
```

i have tried to import a quasar.variable.styl file with some custom variables but this does not work.

```styl
$primary = #00ffff
$toolbar-background = rgba($primary,0.4)
```

**Comment by rstoenescu** [comment] 2017-04-26 20:31
Seems like @mwarren2 did not implement this feature yet.
@mwarren2 can we implement this for the Meteor starter kit?

**Comment by mwarren2** [comment] 2017-04-26 21:00
@nigeltiany Reading the docs for the mquandalle package there's a line which says:

> If you want to @import a file, give it the extension .import.styl to prevent
> Meteor from processing it independently.

Have you tried changing the name of the file to _quasar.variables.import.styl_ ?

**Comment by rstoenescu** [comment] 2017-04-27 07:50
@mwarren2 I see no `quasar.variables.styl` file in the template. Got a few questions:
1. Is it possible to use npm to manage Quasar's distributables/code?
2. How would someone upgrade Quasar version being used?

**Comment by mwarren2** [comment] 2017-04-27 08:53
@rstoenescu  The `quasar.variables.styl` I mentioned was in the bit of gated code in @nigeltiany 's post. 
`// @import '../quasar/quasar.variables.styl'` so I assumed that was the bit of code causing his problem.
1. If you look at the correspondence I had with you on the forum I tried for a long time to make Quasar work with meteor using npm, and it did work for a while, sort of. 
Please see [http://forum.quasar-framework.org/topic/47/meteor/60](url) dated 20 Mar 2017, 14:56. You will see that eventually I had to give up due to webpack.
2. For the reasons in 1. it is therefore admittedly not easy for someone to upgrade the Quasar version used.

So I wrote in the Readme the following, to give an indication of how to upgrade:

> You cannot 'npm install' the quasar-framework in a meteor app, because quasar needs webpack, and meteor, for simplicity, does not use webpack.

> So we have created a quasar folder in /imports, and there we have copied 'quasar.es6.js' from the /dist folder in the npm installation, along with some css files.

If you think this can all be improved, let me know

**Comment by rstoenescu** [comment] 2017-04-27 09:06
@mwarren2 Thanks for detailing. I'll take a closer look to this issue after v0.14 release. Then we'll make this starter kit official too.

**Comment by mwarren2** [comment] 2017-04-27 09:39
Thanks @rstoenescu that's good news.
Meanwhile @nigeltiany sorry if I can't solve your immediate problem easily.

But as you can see, we will be working on it!

**Comment by nigeltiany** [comment] 2017-04-27 19:12
@rstoenescu @mwarren2 alright. I'll let you know if i find out anything that can help.

**Comment by mwarren2** [comment] 2017-05-09 15:43
@rstoenescu Good news. 
It looks like meteor is going to sort out transpiling in the next Meteor version (1.5)

Here's the [bug link](https://github.com/meteor/meteor/issues/8640)

So I should be able to go back to installing from npm.
There is a beta of 1.5 that has been around for a while so I will start experimenting asap.

**Comment by rstoenescu** [comment] 2017-05-09 15:45
@mwarren2 Wow. This is really good news! Thanks for the update.

**Comment by mwarren2** [comment] 2017-05-17 12:08
@rstoenescu I apologize for the delay, but there's a problem with a third-party bridge meteor <->vue that is crashing, and I've been stuck for a week now.

**Comment by rstoenescu** [comment] 2017-05-17 12:10
@mwarren2 no worries, don't be pressured by this. Thx for your efforts!

**Comment by mwarren2** [comment] 2017-06-02 14:07
@rstoenescu Meteor 1.5 is just out and unfortunately this has not been solved but the new release.

The issue is still open and we will just have to hope that it is reasonably high on their todo list.

**Comment by mwarren2** [comment] 2017-06-07 07:48
@rstoenescu  Now assigned to a [feature request](https://github.com/meteor/meteor-feature-requests/issues/6#issuecomment-306636673) 

It's being followed by quite a few people so I think it will get done reasonably soon.

**Comment by mwarren2** [comment] 2017-06-28 15:46
@nigeltiany I've solved this and it now installs from npm.

A little file called

`.vueignore`

was needed in the root folder to ignore .vue files when compiling.
You can read about it on [this page](https://github.com/meteor-vue/vue-meteor/tree/master/packages/vue-component)

So I am closing this.

@rstoenescu I've updated **README.md**, which I see you have beautified. I hope to find time to do a slightly more interesting app at some stage.

**Closed** 2017-06-28 15:50 UTC
