### ISSUE TITLE
[Query] Quasar plugins (eg: Notify) and extras (eg: icons)

### ISSUE THREAD

**Issue by Noboxulus** [quasarframework/quasar-template-meteor#23] opened 2018-04-04 08:49 UTC
May I know how to use Quasar plugins and extras using this template?

I've tried the following and they didn't work.

Notify #1:
```
.....
import { Notify } from '/node_modules/quasar-framework/dist/quasar.mat.common.js';
.....
this.$q.notify("hi");
.....
```
Error:

`[Vue warn]: Error in event handler for "click": "TypeError: this.$q.notify is not a function"`

Notify #2:
```
.....
import { Notify } from '/node_modules/quasar-framework/dist/quasar.mat.common.js';
.....
Notify.create('hi');
.....
```
Error:

`[Vue warn]: Error in event handler for "click": "TypeError: Cannot read property 'add' of undefined"`

**Comment by rstoenescu** [comment] 2018-04-04 10:34
Hi,

Duplicate of Notify plugin not working #22
Please check that. Thanks.

**Closed by rstoenescu** 2018-04-04 10:34 UTC

**Comment by Noboxulus** [comment] 2018-04-05 04:09
@rstoenescu 
Pardon my negligence to mention that this issue was opened after I attempted the #22 solution and failed.
I edited the initial issue accordingly.
Thank you for pointing it out.

**Comment by antoineschaller** [comment] 2018-04-05 09:34
Hi @Noboxulus 

The plugin installation should be done at Vue initialisation (line 27 https://github.com/quasarframework/quasar-template-meteor/blob/master/template/client/main.js). Simply add `plugins: {Notify}` to ``Vue.use(Quasar, {})`:

You will need to import Notify from '/node_modules/quasar-framework/dist/quasar.mat.common.js' as well:

`import Quasar, { Notify} from '/node_modules/quasar-framework/dist/quasar.mat.common.js';`

`Vue.use(Quasar, {
    plugins: {
      Notify,
    },
  });`

**Comment by antoineschaller** [comment] 2018-04-05 09:35
Hi @Noboxulus 

The plugin installation should be done at Vue initialisation (line 27 https://github.com/quasarframework/quasar-template-meteor/blob/master/template/client/main.js). Simply add `plugins: {Notify}` to `Vue.use(Quasar, {})`:

You will need to import Notify from '/node_modules/quasar-framework/dist/quasar.mat.common.js' as well. Which gives you:

`import Quasar, { Notify} from '/node_modules/quasar-framework/dist/quasar.mat.common.js';`

`Vue.use(Quasar, {
    plugins: {
      Notify,
    },
  });`

**Comment by Noboxulus** [comment] 2018-04-06 11:33
@antoineschaller It works! Thank you for your help!
