### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by arezaee** [quasarframework/quasar-template-meteor#44] opened 2019-05-13 13:52 UTC
hi, 
this is a great work, and I like to use it. 

I want to enable RTL support
in the quasar documentation said to change the "quasar.conf.js" file, but that file is missed in this template.
so how can enable it?

thanks

**Comment by mwarren2** [comment] 2019-05-13 14:06
I wish I could help with this.
But there are some things that have been sacrificed when putting Meteor and Quasar together.
And probably RTL support from Quasar is one of those things.

The point is that Meteor does not use the Webpack build system.
Meteor has its own build system, which is extremely simple to use, and is one of its big advantages, to my mind.

What I have done with Meteor is to import Quasar, but to build with Meteor's build system.
This means that the Quasar Cli, and quasar.conf.js are not available in what I have done in **quasar-template-meteor.** 

I suppose it would be nice to try to do everything the other way round, starting with Quasar, and including Meteor in Quasar. But Meteor is not yet available as a simple npm install, and I can't see that happening for some time.

I wish I could help more.

**Comment by nothingismagick** [comment] 2019-05-13 14:08
Yeah - and the issue is that without the CLI - you won't have access to any
app-extensions. Wish there was a way around that... Building from git?

**Comment by mwarren2** [comment] 2019-05-13 14:27
@nothingismagick I hear you and I can see the advantage of app-extensions. But getting it hooked up with Meteor is I guess beyond my capabilities - apart from finding the time to do it - and maybe beyond Meteor's possibilities with Quasar. In particular due to Meteor's decision to keep Webpack out of the story.

**Comment by mwarren2** [comment] 2019-05-14 08:56
@nothingismagick 
```
build: {
  rtl: true
}
```
Can you sum up what this code in quasar.conf.js actually ends up doing in the build?
Is it triggering something fairly simple?

**Comment by mwarren2** [comment] 2019-11-23 13:10
Closing this as unfortunately there is little that I can do in this case

**Closed by mwarren2** 2019-11-23 13:10 UTC
